# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ImageName: 'doaWebApp'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: 'Save image to TAR'
      inputs:
        command: save
        arguments: '--output $(build.artifactstagingdirectory)/$(ImageName).image.tar $(ImageName):$(Build.BuildId)'
        addPipelineData: false
    - task: PublishPipelineArtifact@1
      displayName: 'Publishing Image as Pipeline Artifact'
      inputs:
        path: $(build.artifactstagingdirectory)
        artifact: 'ContainerImage'

